# Generated by Django 4.2.19 on 2025-03-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_created_at_remove_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions provided.', help_text='Step-by-step cooking instructions'),
        ),
    ]
