# Generated by Django 4.2.19 on 2025-03-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
