# Generated by Django 4.2.19 on 2025-04-04 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_recipe_created_at_recipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step-by-step cooking instructions', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='recipes/no_picture.png', upload_to='recipes/'),
        ),
    ]
